MyPortfolioProjectNight/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyPortfolioProjectNight.Models;
using PagedList;
using PagedList.Mvc;

namespace MyPortfolioProjectNight.Controllers
{
    public class DefaultController : Controller
    {

        DbMyPortfolioNightEntities context = new DbMyPortfolioNightEntities();
        // GET: Default

        public ActionResult Index()
        {
            List<SelectListItem> values = (from x in context.Category.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CategoryName,
                                               Value = x.CategoryId.ToString()
                                           }).ToList();
            ViewBag.v = values;
            return View();
        }




        [HttpPost]
        public ActionResult Index(Contact contact)
        {
            contact.SendDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            contact.IsRead = false;

            context.Contact.Add(contact);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        public PartialViewResult PartialHead()
        {
            return PartialView();
        }
        public PartialViewResult PartialScripts()
        {
            return PartialView();
        }
        public PartialViewResult PartialNavbar()
        {
            return PartialView();
        }
        public PartialViewResult PartialHeader()
        {
            ViewBag.title = context.Profile.Select(x=>x.Title).FirstOrDefault();
            ViewBag.description = context.Profile.Select(x=>x.Description).FirstOrDefault();
            ViewBag.address = context.Profile.Select(x=>x.Address).FirstOrDefault();
            ViewBag.email = context.Profile.Select(x=>x.Email).FirstOrDefault();
            ViewBag.phone = context.Profile.Select(x=>x.Phone).FirstOrDefault();
            ViewBag.github = context.Profile.Select(x=>x.Github).FirstOrDefault();
            ViewBag.imageurl = context.Profile.Select(x=>x.ImageUrl).FirstOrDefault();
            return PartialView();
        }
        public PartialViewResult PartialAbout()
        {
            var values = context.About.ToList();
            return PartialView(values);
        }
        public PartialViewResult PartialExperience()
        {
            var values = context.Experience.ToList();
            return PartialView(values);
        }
        public PartialViewResult PartialSkill(int sayfa=1)
        {
            //var values = context.Skill.Where(x => x.Status == true).ToList();

            var values = context.Skill.ToList().ToPagedList(sayfa, 5);
            return PartialView(values);
        }

        //public PartialViewResult OnlyPartialSkills(int sayfa =1)
        //{
        //    var values = context.Skill.ToList().ToPagedList(sayfa,5);
        //    return PartialView(values);
        //}

        public PartialViewResult PartialFooter()
        {
            var values = context.SocialMedia.ToList();
            return PartialView();
        }
        public PartialViewResult PartialEducation()
        {
            var values = context.Education.ToList();
            return PartialView(values);
        }
        public PartialViewResult PartialService()
        {
            var values = context.Service.ToList();
            return PartialView(values);
        }
        public PartialViewResult PartialPortfolio()
        {
            var values = context.Portfolio.ToList();
            return PartialView(values);
        }
        public PartialViewResult PartialTestimonial()
        {
            var values = context.Testimonial.ToList();
            return PartialView(values);
        }
        public PartialViewResult PartialIntern()
        {
            var values = context.Internship.ToList();
            return PartialView(values);
        }
        public PartialViewResult PartialSocialMedia()
        {
            var values = context.SocialMedia.ToList();
            return PartialView(values);
        }

        public PartialViewResult PartialSocialMediaFooter()
        {
            var values = context.SocialMedia.Where(x => x.Status == true).ToList();  //True olanlar gelsin.
            return PartialView(values);
        }

        public PartialViewResult PartialSocialMediaAbout()
        {
            var values = context.SocialMedia.Where(x => x.Status == true).ToList();
            return PartialView(values);
        }

        public PartialViewResult PartialSocialMediaHeader()
        {
            var values = context.SocialMedia.Where(x => x.Status == true).ToList();
            return PartialView(values);
        }

    }
}

MyPortfolioProjectNight/Controllers/PdfController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Policy;
using System.Web;
using System.Web.Mvc;

namespace MyPortfolioProjectNight.Controllers
{
    public class PdfController : Controller
    {
        // GET: Pdf
        public ActionResult ShowPdf()
        {
            // PDF dosyasının yolu (örnek olarak "pdfs" klasöründeki "sample.pdf")  //View klasorunune mumkun mertebe bırakmayın.
            string filePath = Server.MapPath("~/Content/cv.pdf");

            // PDF dosyasını byte dizisi olarak oku
            byte[] fileBytes = System.IO.File.ReadAllBytes(filePath);

            // PDF dosyasını tarayıcıda görüntüle
            return File(fileBytes, "application/pdf");
        }
    }
}

MyPortfolioProjectNight/Views/Default/OnlyPartialSkills.cshtml
@model PagedList.IPagedList<MyPortfolioProjectNight.Models.Skill>
@using PagedList;


@foreach (var item in Model)
{
    <div class="col-6 col-md-4 col-lg-4 col-xl-3">
        <div class="skills-item text-center rounded p-4 h-100 wow fadeInUp" data-wow-delay="0.1s">
            <div class="text-primary text-center mb-3"><span class="@item.Icon"></span></div>

            <div class="counter-counting d-flex justify-content-center">
                <h4 class="display-6" data-toggle="counter-up">@item.Rate</h4>
                <h4 class="display-6"></h4>
            </div>
            <p class="mb-0">@item.SkillName</p>
        </div>
    </div>
}




<!-- Sayfalama Linkleri -->
<div class="pagination-container">
    <ul class="pagination">
        @if (Model.HasPreviousPage)
        {
            <li class="page-item">
                <a href="javascript:void(0)" class="page-link" onclick="loadPage(@(Model.PageNumber - 1))">Önceki</a>
            </li>
        }

        @for (int i = 1; i <= Model.PageCount; i++)
        {
            <li class="page-item @(i == Model.PageNumber ? "active" : "")">
                <a href="javascript:void(0)" class="page-link" onclick="loadPage(@i)">@i</a>
            </li>
        }

        @if (Model.HasNextPage)
        {
            <li class="page-item">
                <a href="javascript:void(0)" class="page-link" onclick="loadPage(@(Model.PageNumber + 1))">Sonraki</a>
            </li>
        }
    </ul>
</div>

<script type="text/javascript">
function loadPage(page) {
    $.ajax({
        url: '@Url.Action("OnlyPartialSkills", "Default")', // Controller'ın action'ı çağrılıyor
        data: { sayfa: page }, // Sayfa numarasını gönderiyoruz
        success: function (result) {
            $('#partial-content').html(result); // Partial view içerisine yeni sonucu yüklüyoruz
        }
    });
}
</script>

MyPortfolioProjectNight/Views/Default/PartialAbout.cshtml
@model List<MyPortfolioProjectNight.Models.About>


@foreach (var item in Model)
{
    <div class="container-fluid" id="pigraAbout">
        <div class="container">
            <div class="row g-0">
                <div class="col-12 col-lg-3">
                    <div class="about-header bg-dark h-100 pt-6 pe-6 pb-6">
                        <div class="text-start d-flex flex-column justify-content-center wow fadeInUp" data-wow-delay="0.1s">
                            <p class="text-white sub-title">Hakkımda</p>
                            <h1 class="display-6 text-white mb-0">Yazılım Eğitim Danışmanlık</h1>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-lg-9">
                    <div class="about-content h-100 pt-6 ps-6 pb-6">
                        <div class="row g-5">
                            <div class="col-xl-5">
                                <div class="about-img bg-light p-4 wow fadeInUp" data-wow-delay="0.1s">
                                    <img src="@item.ImageUrl" class="img-fluid w-100" alt="Image">
                                    <div class="sosial-icon">
                                        <a class="btn btn-primary btn-sm-square mb-3" href="#"><i class="fab fa-facebook-f text-white"></i></a>
                                        <a class="btn btn-primary btn-sm-square mb-3" href="#"><i class="fab fa-twitter text-white"></i></a>
                                        <a class="btn btn-primary btn-sm-square mb-3" href="#"><i class="fab fa-instagram text-white"></i></a>
                                        <a class="btn btn-primary btn-sm-square mb-0" href="#"><i class="fab fa-linkedin-in text-white"></i></a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-7 wow fadeInUp" data-wow-delay="0.3s">
                                <h4 class="mb-4">@item.Title</h4>
                                <p class="mb-4">
                                    @item.Description
                                </p>

                                <a href="@Url.Action("ShowPdf", "Pdf")" target="_blank" })" class="btn btn-primary py-2 px-4"> <i class="fas fa-download me-2"></i>CV mi Görüntüle</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

MyPortfolioProjectNight/Views/Default/PartialEducation.cshtml
@model List<MyPortfolioProjectNight.Models.Education>

<div class="container-fluid" id="pigraEducation">
    <div class="container">
        <div class="row g-0">
            <div class="col-lg-3">
                <div class="education-header bg-dark h-100 pt-6 pe-6 pb-6">
                    <div class="text-start d-flex flex-column justify-content-center wow fadeInUp" data-wow-delay="0.1s">
                        <p class="text-white sub-title">Eğitim</p>
                        <h1 class="display-6 text-white mb-0">Eğitim yeterliliğim</h1>
                    </div>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="education-content h-100 pt-6 ps-6 pb-6">
                    <div class="row g-4">
                        @foreach (var item in Model)
                        {
                            <div class="col-12">
                                <div class="education-item rounded p-4 h-100 wow fadeInUp" data-wow-delay="0.1s">
                                    <div class="d-flex align-items-center mb-3">
                                        <p class="fs-5 mb-0 me-4">@item.Title</p>
                                        <div>
                                            <span class="fa fa-calendar me-1"></span>
                                        </div>
                                    </div>
                                    <h4 class="mb-3">@item.SubTitle</h4>
                                    <p class="mb-0">
                                        @item.Description
                                    </p>
                                </div>
                            </div>
                        }

                        @*<div class="col-12">
                            <div class="education-item rounded p-4 h-100 wow fadeInUp" data-wow-delay="0.3s">
                                <div class="d-flex align-items-center mb-3">
                                    <p class="fs-5 mb-0 me-4">Webster College</p>
                                    <div>
                                        <span class="fa fa-calendar me-1"></span> 2017 - 2019
                                    </div>
                                </div>
                                <h4 class="mb-3">UI/UX Design</h4>
                                <p class="mb-0">
                                    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti, a quasi velit sint atque non saepe quaerat ducimus, nobis error cupiditate, nisi repudiandae dignissimos magnam? Dicta ab possimus tempora nobis.
                                </p>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="education-item rounded p-4 h-100 wow fadeInUp" data-wow-delay="0.5s">
                                <div class="d-flex align-items-center mb-3">
                                    <p class="fs-5 mb-0 me-4">Oxford University</p>
                                    <div>
                                        <span class="fa fa-calendar me-1"></span> 2017 - 2019
                                    </div>
                                </div>
                                <h4 class="mb-3">Java Development</h4>
                                <p class="mb-0">
                                    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti, a quasi velit sint atque non saepe quaerat ducimus, nobis error cupiditate, nisi repudiandae dignissimos magnam? Dicta ab possimus tempora nobis.
                                </p>
                            </div>
                        </div>*@
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

MyPortfolioProjectNight/Views/Default/PartialExperience.cshtml
@model List<MyPortfolioProjectNight.Models.Experience>

<div class="container-fluid" id="pigraExperience">
    <div class="container">
        <div class="row g-0">
            <div class="col-lg-3">
                <div class="experience-header bg-dark h-100 pt-6 pe-6 pb-6">
                    <div class="text-start d-flex flex-column justify-content-center wow fadeInUp" data-wow-delay="0.1s">
                        <p class="text-white sub-title">Deneyimlerim</p>
                        <h1 class="display-6 text-white mb-0">Çalıştığım kurum ve firmalar</h1>
                    </div>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="experience-content h-100 pt-6 ps-6 pb-6">
                    <div class="row g-4">
                        @foreach (var item in Model)
                        {
                            <div class="col-12">
                                <div class="experience-item rounded p-4 h-100 wow fadeInUp" data-wow-delay="0.1s">
                                    <div class="d-flex align-items-center mb-3">
                                        <p class="fs-5 mb-0 me-4">@item.Title</p>
                                        <div>
                                            <span class="fa fa-calendar me-1"></span> 2017 - 2019
                                        </div>
                                    </div>
                                    <h4 class="mb-3">@item.SubTitle</h4>
                                    <p class="mb-0">
                                        @item.Description
                                    </p>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

MyPortfolioProjectNight/Views/Default/PartialFooter.cshtml
@model List<MyPortfolioProjectNight.Models.SocialMedia>



<div class="container-fluid footer bg-dark border-bottom-0">
    <div class="container wow fadeIn" data-wow-delay="0.1s">
        <div class="row g-0">
            <div class="col-12">
                <div class="footer-content h-100 pt-6 ps-6 pb-6">
                    <div class="row g-4 align-items-center">
                        <div class="col-12 text-center">
                            @Html.Action("PartialSocialMediaFooter", "Default")
                        </div>
                        <div class="col-12 text-center">
                            <span class="text-body"><a href="#" class="border-bottom text-white"><i class="fas fa-copyright text-body me-2"></i>Hasan BİLİK</a>, Tüm hakları saklıdır.</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

MyPortfolioProjectNight/Views/Default/PartialHead.cshtml
<head>
    <meta charset="utf-8">
    <title>Portfolio Projesi</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=Edu+TAS+Beginner:wght@400..700&family=Jost:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link rel="/Content/Pigra-1.0.0/stylesheet" href="lib/animate/animate.min.css" />
    <link href="/Content/Pigra-1.0.0/lib/lightbox/css/lightbox.min.css" rel="stylesheet">
    <link href="/Content/Pigra-1.0.0/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">


    <!-- Customized Bootstrap Stylesheet -->
    <link href="/Content/Pigra-1.0.0/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="/Content/Pigra-1.0.0/css/style.css" rel="stylesheet">
</head>

MyPortfolioProjectNight/Views/Default/PartialHeader.cshtml
<div class="container-fluid" id="pigraHome">
    <div class="container">
        <div class="row g-0">
            <div class="col-12 col-lg-3">
                <div class="header-content bg-dark h-100 pt-6 pe-6 pb-6">
                    <a href="index.html" class="navbar-brand d-inline-flex pb-5 wow fadeInUp" data-wow-delay="0.1s">
                        <h1 class="display-6 text-white mb-0">Portfolio</h1>
                    </a>
                    <div class="text-start d-flex flex-column justify-content-center wow fadeInUp" data-wow-delay="0.3s">
                        <p class="text-white sub-title">👋 Merhaba, Ben Hasan BİLİK</p>
                        <h1 class="display-6 text-white mb-0">Yazılım Geliştirici</h1>
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-9">
                <div class="header-img d-flex h-100 pt-6 ps-6 pb-6">
                    <div class="row g-5">
                        <div class="col-xl-6 wow fadeInUp" data-wow-delay="0.1s">
                            <div class="bg-light p-4" style="border-radius: 68% 32% 100% 0% / 0% 75% 25% 100%;">
                                <img src="@ViewBag.imageUrl" class="img-fluid w-100" style="border-radius: 68% 32% 100% 0% / 0% 75% 25% 100%;" alt="Image">
                            </div>
                        </div>
                        <div class="col-xl-6 wow fadeInUp" data-wow-delay="0.3s">
                            <h1 class="display-6 mb-4">@ViewBag.title</h1>
                            <p class="mb-4">
                                @ViewBag.description
                            </p>
                            <div class="d-flex align-items-center mb-2">
                                <i class="fas fa-map-marker-alt text-primary me-3"></i>
                                <p class="text-dark mb-0">@ViewBag.address</p>
                            </div>
                            <div class="d-flex align-items-center mb-2">
                                <i class="fas fa-envelope text-primary me-3"></i>
                                <p class="text-dark mb-0">@ViewBag.email</p>
                            </div>
                            <div class="d-flex align-items-center mb-2">
                                <i class="fa fa-phone-alt text-primary me-3"></i>
                                <p class="text-dark mb-0">@ViewBag.phone</p>
                            </div>
                            <div class="d-flex align-items-center mb-4">
                                <i class="fab fa-firefox-browser text-primary me-3"></i>
                                <p class="text-dark mb-0">@ViewBag.github</p>
                            </div>
                            <div class="d-flex">
                                <a class="btn btn-primary btn-sm-square me-3" href="#"><i class="fab fa-facebook-f text-white"></i></a>
                                <a class="btn btn-primary btn-sm-square me-3" href="#"><i class="fab fa-twitter text-white"></i></a>
                                <a class="btn btn-primary btn-sm-square me-3" href="#"><i class="fab fa-instagram text-white"></i></a>
                                <a class="btn btn-primary btn-sm-square me-0" href="#"><i class="fab fa-linkedin-in text-white"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

MyPortfolioProjectNight/Views/Default/PartialNavbar.cshtml
<div class="container-fluid nav-section border-0">
    <nav class="navbar navbar-light">
        <div class="navbar-nav flex-column">
            <a href="#pigraHome" class="nav-item nav-link active"><span class="fa fa-home"></span>Anasayfa</a>
            <a href="#pigraAbout" class="nav-item nav-link"><span class="far fa-address-card"></span> Hakkımda</a>
            <a href="#pigraService" class="nav-item nav-link"><span class="fab fa-servicestack"></span> Hizmetler</a>
            <a href="#pigraEducation" class="nav-item nav-link"><span class="fas fa-school"></span> Eğitim</a>
            <a href="#pigraExperience" class="nav-item nav-link"><span class="fa fa-blog"></span>Deneyim</a>
            <a href="#pigraSkill" class="nav-item nav-link"><span class="far fa-address-card"></span> Yeteneklerim</a>
            <a href="#pigraPortfolio" class="nav-item nav-link"><span class="fa fa-blog"></span> Portfolyo</a>
            <a href="#pigraIntern" class="nav-item nav-link"><span class="fa fa-battery-three-quarters"></span>Staj</a>
            <a href="#pigraTestimonial" class="nav-item nav-link"><span class="fab fa-servicestack"></span>Referans</a>
            <a href="#pigraContact" class="nav-item nav-link"><span class="fas fa-address-book"></span>Bana Yazın</a>
        </div>
    </nav>
</div>

MyPortfolioProjectNight/Views/Default/PartialPortfolio.cshtml
@model List<MyPortfolioProjectNight.Models.Portfolio>

<div class="container-fluid" id="pigraPortfolio">
    <div class="container">
        <div class="row g-0">
            <div class="col-lg-3">
                <div class="portfolio-header h-100 bg-dark pt-6 pe-6 pb-6">
                    <div class="text-start d-flex flex-column justify-content-center wow fadeInUp" data-wow-delay="0.1s">
                        <p class="text-white sub-title">Portfolio</p>
                        <h1 class="display-6 text-white mb-0">Son Çalışmalarım</h1>
                    </div>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="portfolio-content h-100 pt-6 ps-6 pb-6">


                    @foreach (var item in Model)
                    {
                        <div class="portfolio-item py-5 border-bottom wow fadeInUp" data-wow-delay="0.1s">
                            <div class="row g-4 align-items-center">
                                <div class="col-xl-6">
                                    <h4 class="text-body">@item.PortfolioTitle</h4>
                                    <h1 class="display-6 mb-0">@item.PortfolioSubTitle</h1>
                                </div>
                                <div class="col-9 col-xl-4">
                                    <div class="portfolio-img">
                                        <div class="portfolio-img-inner">
                                            <img src="@item.PortfolioImageUrl" class="img-fluid" alt="Image">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-3 col-xl-2">
                                    <div class="view-img">
                                        <a href="@item.PortfolioImageUrl" class="btn btn-primary btn-lg-square" data-lightbox="Portfolio-1"><i class="fas fa-plus"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }




                    @*<div class="portfolio-item py-5 border-bottom wow fadeInUp" data-wow-delay="0.3s">
                        <div class="row g-4 align-items-center">
                            <div class="col-xl-6">
                                <h4 class="text-body">Web Development</h4>
                                <h1 class="display-6 mb-0">Website Development for ABC Corporation</h1>
                            </div>
                            <div class="col-9 col-xl-4">
                                <div class="portfolio-img">
                                    <div class="portfolio-img-inner">
                                        <img src="img/portfolio-2.jpg" class="img-fluid" alt="Image">
                                    </div>
                                </div>
                            </div>
                            <div class="col-3 col-xl-2">
                                <div class="view-img">
                                    <a href="img/portfolio-2.jpg" class="btn btn-primary btn-lg-square" data-lightbox="portfolio-2"><i class="fas fa-plus"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="portfolio-item py-5 wow fadeInUp" data-wow-delay="0.5s">
                        <div class="row g-4 align-items-center">
                            <div class="col-xl-6">
                                <h4 class="text-body">Photography</h4>
                                <h1 class="display-6 mb-0">Security Analysis for ABC Corporation</h1>
                            </div>
                            <div class="col-9 col-xl-4">
                                <div class="portfolio-img">
                                    <div class="portfolio-img-inner">
                                        <img src="img/portfolio-3.jpg" class="img-fluid" alt="Image">
                                    </div>
                                </div>
                            </div>
                            <div class="col-3 col-xl-2">
                                <div class="view-img">
                                    <a href="img/portfolio-3.jpg" class="btn btn-primary btn-lg-square" data-lightbox="portfolio-3"><i class="fas fa-plus"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>*@





                </div>
            </div>
        </div>
    </div>
</div>

MyPortfolioProjectNight/Views/Default/PartialSkill.cshtml
@model PagedList.IPagedList<MyPortfolioProjectNight.Models.Skill>
@using PagedList;

<div class="container-fluid" id="pigraSkill">
    <div class="container">
        <div class="row g-0">
            <div class="col-lg-3">
                <div class="skills-header h-100 bg-dark pt-6 pe-6 pb-6">
                    <div class="text-start d-flex flex-column justify-content-center wow fadeInUp" data-wow-delay="0.1s">
                        <p class="text-white sub-title">Yeteneklerim</p>
                        <h1 class="display-6 text-white mb-0">Programlama Dilleri ve Teknolojileri</h1>
                    </div>
                </div>
            </div>
            <div class="col-lg-9">

                <div class="skills-content h-100 pt-6 ps-6 pb-6">
                    <div class="row g-4" id="partial-content">
                        @foreach (var item in Model)
                        {
                            <div class="col-6 col-md-4 col-lg-4 col-xl-3">
                                <div class="skills-item text-center rounded p-4 h-100 wow fadeInUp" data-wow-delay="0.1s">
                                    <div class="text-primary text-center mb-3"><span class="@item.Icon"></span></div>

                                    <div class="counter-counting d-flex justify-content-center">
                                        <h4 class="display-6" data-toggle="counter-up">@item.Rate</h4>
                                        <h4 class="display-6"></h4>
                                    </div>
                                    <p class="mb-0">@item.SkillName</p>
                                </div>
                            </div>
                        }

                        <!-- SAYFALAMA LİNKLERİ -->
                        <!--<div class="pagination-container">
                            <ul class="pagination">
                                @if (Model.HasPreviousPage)
                                {
                                    <li class="page-item">
                                        <a href="javascript:void(0)" class="page-link" onclick="loadPage(@(Model.PageNumber - 1))">Önceki</a>
                                    </li>
                                }

                                @for (int i = 1; i <= Model.PageCount; i++)
                                {
                                    <li class="page-item @(i == Model.PageNumber ? "active" : "")">
                                        <a href="javascript:void(0)" class="page-link" onclick="loadPage(@i)">@i</a>
                                    </li>
                                }

                                @if (Model.HasNextPage)
                                {
                                    <li class="page-item">
                                        <a href="javascript:void(0)" class="page-link" onclick="loadPage(@(Model.PageNumber + 1))">Sonraki</a>
                                    </li>
                                }
                            </ul>
                        </div>

                        <script type="text/javascript">
    function loadPage(page) {
        $.ajax({
            url: '@Url.Action("OnlyPartialSkills", "Default")', // Controller'ın action'ı çağrılıyor
            data: { sayfa: page }, // Sayfa numarasını gönderiyoruz
            success: function (result) {
                $('#partial-content').html(result); // Partial view içerisine yeni sonucu yüklüyoruz
            }
        });
    }
                        </script>-->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>